// <auto-generated />
using System;
using AgendaWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgendaWebAPI.Migrations
{
    [DbContext(typeof(AgendaContext))]
    partial class AgendaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("AgendaWebAPI.Models.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Contatos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "peterpark@gmail.com",
                            Nome = "Peter",
                            Sobrenome = "Parker",
                            Telefone = "99999999"
                        },
                        new
                        {
                            Id = 2,
                            Email = "mjackson@hotmail.com",
                            Nome = "Michael",
                            Sobrenome = "Jackson",
                            Telefone = "888888888"
                        },
                        new
                        {
                            Id = 3,
                            Email = "jw92@gmail.com",
                            Nome = "Jorge",
                            Sobrenome = "Wilson",
                            Telefone = "483948394"
                        },
                        new
                        {
                            Id = 4,
                            Email = "mariapaula@hotmail.com",
                            Nome = "Maria",
                            Sobrenome = "Paula",
                            Telefone = "123923834"
                        });
                });

            modelBuilder.Entity("AgendaWebAPI.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Data = new DateTime(2021, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Reunião Gerencial"
                        },
                        new
                        {
                            Id = 2,
                            Data = new DateTime(1991, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Aniversario"
                        },
                        new
                        {
                            Id = 3,
                            Data = new DateTime(2021, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Curso ASP.NET Core"
                        });
                });

            modelBuilder.Entity("AgendaWebAPI.Models.PessoaEvento", b =>
                {
                    b.Property<int>("ContatoId")
                        .HasColumnType("int");

                    b.Property<int>("EventoId")
                        .HasColumnType("int");

                    b.HasKey("ContatoId", "EventoId");

                    b.HasIndex("EventoId");

                    b.ToTable("PessoasEventos");

                    b.HasData(
                        new
                        {
                            ContatoId = 1,
                            EventoId = 2
                        },
                        new
                        {
                            ContatoId = 1,
                            EventoId = 3
                        },
                        new
                        {
                            ContatoId = 2,
                            EventoId = 1
                        },
                        new
                        {
                            ContatoId = 3,
                            EventoId = 1
                        },
                        new
                        {
                            ContatoId = 3,
                            EventoId = 3
                        });
                });

            modelBuilder.Entity("AgendaWebAPI.Models.PessoaEvento", b =>
                {
                    b.HasOne("AgendaWebAPI.Models.Contato", "Contato")
                        .WithMany("PessoasEventos")
                        .HasForeignKey("ContatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgendaWebAPI.Models.Evento", "Evento")
                        .WithMany("PessoasEventos")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contato");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("AgendaWebAPI.Models.Contato", b =>
                {
                    b.Navigation("PessoasEventos");
                });

            modelBuilder.Entity("AgendaWebAPI.Models.Evento", b =>
                {
                    b.Navigation("PessoasEventos");
                });
#pragma warning restore 612, 618
        }
    }
}
